# Database configuration
database_url = "sqlite:///abdalla.db"

# Groq API configuration
groq_api_key = "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"

# # Application settings
# debug = false